services:
  - type: web
    name: synthcloud
    runtime: docker
    repo: https://github.com/HGerdes/SynthCloud.git
    region: ohio
    plan: starter
    buildCommand: pip install -r requirements.txt
    preDeployCommand: flask db upgrade
    envVars:
      - key: DATABASE_URL
        value: postgres://synthcloud_admin:cDZKfVJzec9aGCGIeIyZ9AzcmqCuSEMC@dpg-cl0m3bk8s0fs73er3ru0-a/synthcloud_db_4zh1

databases:
  - name: synthcloud_db
    databaseName: synthdb
    user: synthcloud_admin
    
