services:
  - type: web
    name: synthcloud
    runtime: docker
    repo: https://github.com/HGerdes/SynthCloud.git
    region: ohio
    plan: free
    preDeployCommand: flask db upgrade && flask seed all
    buildCommand: pip install -r requirements.txt
    envVars:
      - key: DATABASE_URL
        value: postgres://harrison:phzOvUafuhtufuzhyA3677zi2Jjm5uHL@dpg-cl0khl237rbc73cb5fk0-a/synthcloud_db

databases:
  - name: synthcloud_db
    user: harrison
