services:
  - type: web
    name: synthcloud
    runtime: docker
    repo: https://github.com/HGerdes/SynthCloud.git
    region: ohio
    plan: free
    preDeployCommand: flask db upgrade
    buildCommand: pip install -r requirements.txt
    envVars:
      - key: DATABASE_URL
        value: postgres://harrison:cDZKfVJzec9aGCGIeIyZ9AzcmqCuSEMC@dpg-cl0m3bk8s0fs73er3ru0-a/synthcloud_db_4zh1

databases:
  - name: synthcloud_db
    user: harrison
