"""empty message

Revision ID: 028936de7a00
Revises: 201b33047e29
Create Date: 2021-11-18 21:01:01.156751

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '028936de7a00'
down_revision = '201b33047e29'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tracks', sa.Column('image_url', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tracks', 'image_url')
    # ### end Alembic commands ###
