"""empty message

Revision ID: 201b33047e29
Revises: 9f0a2639d07d
Create Date: 2021-11-18 19:24:36.137241

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '201b33047e29'
down_revision = '9f0a2639d07d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tracks', 'album_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tracks', 'album_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
